import type { WishlistItem, Folder } from './types';

// Mock data - in a real app, this would come from global state/context
export const mockWishlistData: WishlistItem[] = [
  {
    id: '1',
    name: 'Brew & Bites',
    tagline: 'Premium Coffee & Artisanal Snacks',
    category: 'Food & Beverage',
    investmentRange: '₹25L - ₹40L',
    roi: '35-45%',
    paybackPeriod: '18-24 months',
    monthlyRevenue: '₹4.5L - ₹7L',
    location: 'Pan India',
    rating: 4.8,
    reviews: 128,
    image: 'https://images.unsplash.com/photo-1497935586351-b67a49e012bf?w=800&auto=format&fit=crop', // Updated to a fresh coffee image
    tags: ['Franchise', 'Premium', 'Quick ROI'],
    isVerified: true,
    addedAt: '2024-04-05T10:30:00Z',
  },
  {
    id: '2',
    name: 'Fitness Pro Gym',
    tagline: 'State-of-the-Art Fitness Center',
    category: 'Health & Fitness',
    investmentRange: '₹50L - ₹80L',
    roi: '40-50%',
    paybackPeriod: '24-30 months',
    monthlyRevenue: '₹8L - ₹12L',
    location: 'Metro Cities',
    rating: 4.6,
    reviews: 89,
    image: 'https://images.unsplash.com/photo-1534438327276-14e5300c3a48?w=800&auto=format&fit=crop',
    tags: ['Scalable', 'High Growth'],
    isVerified: true,
    addedAt: '2024-04-04T14:20:00Z',
  },
  {
    id: '3',
    name: 'TechHub Co-working',
    tagline: 'Smart Office Spaces for Startups',
    category: 'Real Estate',
    investmentRange: '₹1Cr - ₹2Cr',
    roi: '25-35%',
    paybackPeriod: '36-48 months',
    monthlyRevenue: '₹15L - ₹25L',
    location: 'Tier 1 Cities',
    rating: 4.9,
    reviews: 156,
    image: 'https://images.unsplash.com/photo-1497366216548-37526070297c?w=800&auto=format&fit=crop',
    tags: ['B2B', 'Premium', 'Stable Returns'],
    isVerified: true,
    addedAt: '2024-04-04T15:20:00Z',
  },
  {
    id: '4',
    name: 'Quick Mart Convenience',
    tagline: '24/7 Neighborhood Convenience Store',
    category: 'Retail',
    investmentRange: '₹30L - ₹50L',
    roi: '30-40%',
    paybackPeriod: '20-28 months',
    monthlyRevenue: '₹5L - ₹8L',
    location: 'Residential Areas',
    rating: 4.5,
    reviews: 72,
    image: 'https://images.unsplash.com/photo-1578916171728-46686eac8d58?w=800&auto=format&fit=crop',
    tags: ['Turnkey', 'Essential Business'],
    isVerified: true,
    addedAt: '2024-04-03T11:45:00Z',
  },
  {
    id: '5',
    name: 'PetPal Paradise',
    tagline: 'Pet Grooming & Care Services',
    category: 'Pet Services',
    investmentRange: '₹20L - ₹35L',
    roi: '45-55%',
    paybackPeriod: '15-20 months',
    monthlyRevenue: '₹3.5L - ₹6L',
    location: 'Urban Areas',
    rating: 4.7,
    reviews: 64,
    image: 'https://images.unsplash.com/photo-1516734212186-a967f81f1480?w=800&auto=format&fit=crop',
    tags: ['Niche Market', 'Emerging', 'High Growth'],
    isVerified: true,
    addedAt: '2024-04-03T09:15:00Z',
  },
  {
    id: '6',
    name: 'Learning Tree Academy',
    tagline: 'K-12 After School Learning Center',
    category: 'Education',
    investmentRange: '₹40L - ₹60L',
    roi: '35-45%',
    paybackPeriod: '24-36 months',
    monthlyRevenue: '₹6L - ₹10L',
    location: 'School Zones',
    rating: 4.8,
    reviews: 95,
    image: 'https://images.unsplash.com/photo-1503676260728-1c00da094a0b?w=800&auto=format&fit=crop',
    tags: ['Community', 'Essential Business', 'Recession Proof'],
    isVerified: true,
    addedAt: '2024-04-02T16:30:00Z',
  },
  {
    id: '7',
    name: 'Green Eats Restaurant',
    tagline: 'Organic & Healthy Fast Food',
    category: 'Food & Beverage',
    investmentRange: '₹35L - ₹55L',
    roi: '38-48%',
    paybackPeriod: '18-24 months',
    monthlyRevenue: '₹7L - ₹11L',
    location: 'Commercial Areas',
    rating: 4.6,
    reviews: 110,
    image: 'https://images.unsplash.com/photo-1517248135467-4c7edcad34c4?w=800&auto=format&fit=crop',
    tags: ['Eco-Friendly', 'Trending'],
    isVerified: true,
    addedAt: '2024-04-01T13:00:00Z',
  },
  {
    id: '8',
    name: 'MedCare Clinic',
    tagline: 'Multi-Specialty Healthcare Center',
    category: 'Healthcare',
    investmentRange: '₹80L - ₹1.2Cr',
    roi: '40-50%',
    paybackPeriod: '30-42 months',
    monthlyRevenue: '₹12L - ₹18L',
    location: 'Residential Hubs',
    rating: 4.9,
    reviews: 180,
    image: 'https://images.unsplash.com/photo-1587351021759-3e566b2af611?w=800&auto=format&fit=crop',
    tags: ['Essential Business', 'Premium', 'Stable Returns'],
    isVerified: true,
    addedAt: '2024-03-31T10:00:00Z',
  },
];

// Initial folders with wishlist items distributed
export const initialFolders: Folder[] = [
  {
    id: 'all',
    name: 'All Items',
    itemIds: mockWishlistData.map(item => item.id),
  },
  {
    id: 'favorites',
    name: 'Favorites',
    itemIds: ['1', '3', '5'],
  },
  {
    id: 'high-roi',
    name: 'High ROI',
    itemIds: ['2', '5'],
  },
];